#!/usr/bin/env python3
"""
gen_dead_data.py
Reads assets/dead_Screen.nss and generates:
  - assets/dead_screen.nam  (raw binary: 960 nametable + 64 attribute bytes)
  - dead_screen_data.fab   (NESFab constants for palette)
"""

import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.join(SCRIPT_DIR, '..')
NSS_PATH  = os.path.join(BASE_DIR, 'assets', 'dead_Screen.nss')
NAM_PATH  = os.path.join(BASE_DIR, 'assets', 'dead_screen.nam')
FAB_PATH  = os.path.join(BASE_DIR, 'src/dead_screen_data.fab')


def decode_nss_bytes(s):
    """Decode NSS compressed hex format like 00[14]01[2] into byte list."""
    result = []
    i = 0
    while i < len(s):
        byte_val = int(s[i:i+2], 16)
        i += 2
        if i < len(s) and s[i] == '[':
            j = s.index(']', i)
            count = int(s[i+1:j], 16)
            result.extend([byte_val] * count)
            i = j + 1
        else:
            result.append(byte_val)
    return result


def main():
    with open(NSS_PATH, 'r', errors='replace') as f:
        content = f.read()

    nt_match   = re.search(r'NameTable=([0-9a-f\[\]]+)', content)
    attr_match = re.search(r'AttrTable=([0-9a-f\[\]]+)', content)
    pal_match  = re.search(r'Palette=([0-9a-f\[\]]+)', content)

    nt      = decode_nss_bytes(nt_match.group(1))    # 960 bytes (32x30)
    attr    = decode_nss_bytes(attr_match.group(1))  # 64 bytes
    pal_raw = decode_nss_bytes(pal_match.group(1))   # 64 bytes

    if len(nt) == 1024:
        nam_data = bytes(nt)
    else:
        nam_data = bytes(nt[:960] + attr[:64])
    with open(NAM_PATH, 'wb') as f:
        f.write(nam_data)
    print(f"Written {NAM_PATH}  ({len(nam_data)} bytes)")

    # --- Parse palette ---
    # NSS palette layout: 4 BG palettes then 4 sprite palettes, each group = 4 bytes
    # Group format: [UBC, color1, color2, color3]
    ubc = pal_raw[0]
    bg_colors = []
    for i in range(4):
        base = i * 4
        bg_colors.extend([pal_raw[base+1], pal_raw[base+2], pal_raw[base+3]])

    # --- Write NESFab palette constants ---
    def hex_list(vals):
        return ', '.join(f'${v:02X}' for v in vals)

    fab_lines = [
        "// AUTO-GENERATED by scripts/gen_dead_data.py -- DO NOT EDIT MANUALLY",
        "// Dead screen palette constants from assets/dead_Screen.nss",
        "",
        "// Dead CHR bank index (MMC3 bank 20)",
        "ct U DEAD_CHR_BANK = 20",
        "",
        "// Load the raw dead screen CHR tiles into MMC3 bank 20 (BG slot, $0000-$1FFF)",
        "chrrom (20 * $2000)",
        "    file(raw, \"assets/dead_screen_CHR.chr\")",
        "",
        "// Universal Background Color",
        f"ct U DEAD_UBC = ${ubc:02X}",
        "",
        "// BG sub-palette colors (3 colors per palette x 4 palettes = 12 values)",
        f"ct U[12] dead_bg_palette = U[12](",
        f"    // Palette 0:  {hex_list(bg_colors[0:3])}",
        f"    {hex_list(bg_colors[0:3])},",
        f"    // Palette 1:  {hex_list(bg_colors[3:6])}",
        f"    {hex_list(bg_colors[3:6])},",
        f"    // Palette 2:  {hex_list(bg_colors[6:9])}",
        f"    {hex_list(bg_colors[6:9])},",
        f"    // Palette 3:  {hex_list(bg_colors[9:12])}",
        f"    {hex_list(bg_colors[9:12])}",
        ")",
        "",
        "// Nametable + attributes loaded from binary .nam file",
        "data /dead",
        "    [] dead_nam",
        "        file(raw, \"assets/dead_screen.nam\")",
        "",
    ]

    with open(FAB_PATH, 'w', newline='\n') as f:
        f.write('\n'.join(fab_lines))
    print(f"Written {FAB_PATH}")
    print(f"  UBC:        ${ubc:02X}")
    print(f"  BG palette: {[hex(c) for c in bg_colors]}")


if __name__ == '__main__':
    main()
