#!/usr/bin/env python3
"""
gen_title_data.py
Reads assets/TitleScreen.nss and generates:
  - assets/TitleScreen.nam  (raw binary: 960 nametable + 64 attribute bytes)
  - title_screen_data.fab   (NESFab constants for palette)
"""

import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.join(SCRIPT_DIR, '..')
NSS_PATH  = os.path.join(BASE_DIR, 'assets', 'TitleScreen.nss')
NAM_PATH  = os.path.join(BASE_DIR, 'assets', 'TitleScreen.nam')
FAB_PATH  = os.path.join(BASE_DIR, 'src/title_screen_data.fab')


def decode_nss_bytes(s):
    """Decode NSS compressed hex format like 00[14]01[2] into byte list."""
    result = []
    i = 0
    while i < len(s):
        byte_val = int(s[i:i+2], 16)
        i += 2
        if i < len(s) and s[i] == '[':
            j = s.index(']', i)
            count = int(s[i+1:j], 16)
            result.extend([byte_val] * count)
            i = j + 1
        else:
            result.append(byte_val)
    return result


def main():
    with open(NSS_PATH, 'r', errors='replace') as f:
        content = f.read()

    nt_match   = re.search(r'NameTable=([0-9a-f\[\]]+)', content)
    attr_match = re.search(r'AttrTable=([0-9a-f\[\]]+)', content)
    pal_match  = re.search(r'Palette=([0-9a-f\[\]]+)', content)

    nt      = decode_nss_bytes(nt_match.group(1))    # 960 bytes (32x30)
    attr    = decode_nss_bytes(attr_match.group(1))  # 64 bytes
    pal_raw = decode_nss_bytes(pal_match.group(1))   # 64 bytes

    assert len(nt) == 960,  f"Expected 960 nametable bytes, got {len(nt)}"
    assert len(attr) == 64, f"Expected 64 attribute bytes, got {len(attr)}"

    # --- Write raw .nam file (nametable + attributes = 1024 bytes) ---
    nam_data = bytes(nt + attr)
    with open(NAM_PATH, 'wb') as f:
        f.write(nam_data)
    print(f"Written {NAM_PATH}  ({len(nam_data)} bytes)")

    # --- Parse palette ---
    # NSS palette layout: 4 BG palettes then 4 sprite palettes, each group = 4 bytes
    # Group format: [UBC, color1, color2, color3]
    ubc = pal_raw[0]
    bg_colors = []
    for i in range(4):
        base = i * 4
        bg_colors.extend([pal_raw[base+1], pal_raw[base+2], pal_raw[base+3]])

    # --- Write NESFab palette constants ---
    def hex_list(vals):
        return ', '.join(f'${v:02X}' for v in vals)

    fab_lines = [
        "// AUTO-GENERATED by scripts/gen_title_data.py -- DO NOT EDIT MANUALLY",
        "// Title screen assets from assets/TitleScreen.nss + assets/title_bg.chr",
        "",
        "// Title CHR bank index (MMC3 bank 0, separate from level CHR at bank 2)",
        "ct U TITLE_CHR_BANK = 0",
        "",
        "// Universal Background Color",
        f"ct U TITLE_UBC = ${ubc:02X}",
        "",
        "// Load the raw title screen CHR tiles into MMC3 bank 0 (BG slot, $0000-$0FFF)",
        "// And load the Game Kitchen logo into the sprite slot ($1000-$1FFF)",
        "chrrom (0 * $2000)",
        "    file(raw, \"../assets/title_bg.chr\")",
        "    file(fmt, \"../assets/game_kitchen_logo.png\")",
        "",
        "// Load Dead Screen background and font into MMC3 Bank 7 (Index 7 = $E000)",
        "chrrom ($E000)",
        "    file(raw, \"../assets/dead_screen_bg.chr\")",
        "    file(fmt, \"../assets/font.png\")",
        "",
        "// BG sub-palette colors (3 colors per palette x 4 palettes = 12 values)",
        f"ct U[12] title_bg_palette = U[12](",
        f"    // Palette 0:  {hex_list(bg_colors[0:3])}",
        f"    {hex_list(bg_colors[0:3])},",
        f"    // Palette 1:  {hex_list(bg_colors[3:6])}",
        f"    {hex_list(bg_colors[3:6])},",
        f"    // Palette 2:  {hex_list(bg_colors[6:9])}",
        f"    {hex_list(bg_colors[6:9])},",
        f"    // Palette 3:  {hex_list(bg_colors[9:12])}",
        f"    {hex_list(bg_colors[9:12])}",
        ")",
        "",
        "// Nametable + attributes loaded from binary .nam file (960 + 64 = 1024 bytes)",
        "data /title",
        "    [] title_nam",
        "        file(raw, \"../assets/TitleScreen.nam\")",
        "",
    ]

    with open(FAB_PATH, 'w', newline='\n') as f:
        f.write('\n'.join(fab_lines))
    print(f"Written {FAB_PATH}")
    print(f"  UBC:        ${ubc:02X}")
    print(f"  BG palette: {[hex(c) for c in bg_colors]}")


if __name__ == '__main__':
    main()
