@echo off
cls

echo Starting Build Pipeline...
python scripts/mapfab_to_json.py
if %errorlevel% neq 0 exit /b %errorlevel%

python scripts/split_maps.py
if %errorlevel% neq 0 exit /b %errorlevel%

python scripts/update_version.py
if %errorlevel% neq 0 exit /b %errorlevel%

:: Read the version generated by update_version.py
set /p VERSION=<VERSION

:: ----------------------------------------------------
:: BUILD 1: RELEASE VERSION (Cheats Disabled)
:: ----------------------------------------------------
echo Building Release version %VERSION%...
python scripts/set_build_flag.py release
if %errorlevel% neq 0 exit /b %errorlevel%

c:\Workspace\NES\nesfab_1_8\nesfab.exe .\BlasNESmous.cfg
if %errorlevel% neq 0 exit /b %errorlevel%

:: Rename the output
move /Y BlasNESmous.nes BlasNESmous_%VERSION%.nes

:: ----------------------------------------------------
:: BUILD 2: DEV VERSION (Cheats Enabled)
:: ----------------------------------------------------
echo Building Dev version...
python scripts/set_build_flag.py dev
if %errorlevel% neq 0 exit /b %errorlevel%

c:\Workspace\NES\nesfab_1_8\nesfab.exe .\BlasNESmous.cfg
if %errorlevel% neq 0 exit /b %errorlevel%

:: Rename the output
copy /Y BlasNESmous.nes BlasNESmous_dev.nes
copy /Y BlasNESmous.mlb BlasNESmous_dev.mlb

:: ----------------------------------------------------
:: ANALYSIS & RUN
:: ----------------------------------------------------
echo Running Post-Build Analysis...
python scripts/analyzeROM.py
python scripts/analyzeCHR.py
python scripts/analyze_metasprites.py
python scripts/analyze_prg_banks.py
python scripts/verify_physics.py

echo Launching Mesen...
start "" c:\Workspace\NES\Mesen\Mesen.exe BlasNESmous_dev.nes