#!/bin/bash
clear

echo "Starting Build Pipeline..."
python3 scripts/mapfab_to_json.py || exit $?
python3 scripts/split_maps.py || exit $?
python3 scripts/update_version.py || exit $?

# Read the version generated by update_version.py
VERSION=$(cat VERSION)

# ----------------------------------------------------
# BUILD 1: RELEASE VERSION (Cheats Disabled)
# ----------------------------------------------------
echo "Building Release version $VERSION..."
python3 scripts/set_build_flag.py release || exit $?
../../nesfab BlasNESmous.cfg || exit $?

# Rename the output
mv BlasNESmous.nes "BlasNESmous_${VERSION}.nes"

# ----------------------------------------------------
# BUILD 2: DEV VERSION (Cheats Enabled)
# ----------------------------------------------------
echo "Building Dev version..."
python3 scripts/set_build_flag.py dev || exit $?
../../nesfab BlasNESmous.cfg || exit $?

# Rename the output
cp BlasNESmous.nes BlasNESmous_dev.nes
cp BlasNESmous.mlb BlasNESmous_dev.mlb

# ----------------------------------------------------
# ANALYSIS & RUN
# ----------------------------------------------------
echo "Running Post-Build Analysis..."
python3 scripts/analyzeROM.py
python3 scripts/analyzeCHR.py
python3 scripts/analyze_metasprites.py
python3 scripts/analyze_prg_banks.py
python3 scripts/verify_physics.py

echo "Launching Mesen..."
~/Downloads/Mesen/Mesen.app/Contents/MacOS/Mesen BlasNESmous_dev.nes &
